disable_for_duration:
  target:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: blocky
    duration:
      required: true
      example: 30m
      selector:
        text:
    groups:
      required: false
      example: ads,tracker
      selector:
        text:
